# Generated by Django 5.1.6 on 2025-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_username",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Enter your telegram chat id (NOT your username that starts with @)",
                max_length=50,
                null=True,
                verbose_name="telegram chat id",
            ),
        ),
    ]
