# Generated by Django 5.1.6 on 2025-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_frequency_alter_habit_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=200, verbose_name="day of week")),
            ],
        ),
        migrations.AddField(
            model_name="habit",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Enter the time when a habit should be performed for the last time per day. Only for good habits that should be performed several times per day!",
                null=True,
                verbose_name="end time",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="days_of_week",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select specific days when a good habit should be performed.",
                null=True,
                to="habits.week",
                verbose_name="day(s) of week",
            ),
        ),
    ]
