# Generated by Django 5.1.6 on 2025-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_week_habit_end_time_habit_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="day",
            field=models.CharField(max_length=3, verbose_name="day of week"),
        ),
    ]
