# Generated by Django 5.1.6 on 2025-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_week_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m x-y * * *", "every hour"),
                    ("m x-y/2 * * *", "every 2 hours"),
                    ("m x-y/3 * * *", "every 3 hours"),
                    ("m x,z,y * * *", "3 times per day"),
                    ("m x,y * * *", "2 times per day"),
                    ("m h * * *", "every day"),
                    ("m h */2 * *", "every 2 days"),
                    ("m h */3 * *", "every 3 days"),
                    ("m h * * d", "selected days"),
                ],
                default="m h * * *",
                help_text="Select how often a good habit should be performed. NOTE! A good habit should be performed once a week at least. For good habits only!",
                null=True,
                verbose_name="frequency",
            ),
        ),
    ]
